SchoolMonitoringSystem.Api/Controllers/FilterController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolMonitoringSystem.Application.Common;
using SchoolMonitoringSystem.Application.UseCases;
using SchoolMonitoringSystem.Application.UseCases.Filters;

namespace SchoolMonitoringSystem.Api.Controllers
{
    public class FilterController : ApiBaseController
    {
        private readonly IApplicationDbContext dbContext;

        public FilterController(IApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public async Task<IActionResult> AgeStudentFilter(AgeStudentFilterQuery ageFilterQuery)
        {
            return View(await Mediator.Send(ageFilterQuery));
        }
        public async Task<IActionResult> DayMonthFilter(DayMonthFilterQuery dayMonthFilter)
        {
            return View(await Mediator.Send(dayMonthFilter));
        }
		public async Task<IActionResult> AgeTeacherFilter(AgeTeacherFilterQuery ageTeacherFilterQuery)
		{
			return View(await Mediator.Send(ageTeacherFilterQuery));
		}
        public async Task<IActionResult> IsBeelineStudentFilter(IsBeelineStudentFilterQuery isBeelineStudentFilter)
		{
			return View(await Mediator.Send(isBeelineStudentFilter));
		}
        public async Task<IActionResult> IsBeelineTeacherFilter(IsBeelineTeacherFilterQuery isBeelineTeacherFilter)
		{
			return View(await Mediator.Send(isBeelineTeacherFilter));
		}
        public async Task<IActionResult> SearchStudentFilter(SearchStudentFilterQuery searchStudentFilter)
		{
			return View(await Mediator.Send(searchStudentFilter));
		}
        public async Task<IActionResult> SearchSubjectFilter(SearchSubjectFilterQuery searchSubjectFilter)
		{
            ViewData["teachers"] = await Mediator.Send(new GetAllTeacherQuery());
            return View(await Mediator.Send(searchSubjectFilter));
		}
        public async Task<IActionResult> SearchTeacherFilter(SearchTeacherFilterQuery searchTeacherFilter)
		{
			return View(await Mediator.Send(searchTeacherFilter));
		}
        [HttpGet]
        public async Task<IActionResult> BestSubjectFilter()
        {
            ViewData["teachers"] = await Mediator.Send(new GetAllTeacherQuery());
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> BestSubjectsFilter(BestSubjectFilterQuery students)
        {
            ViewData["teachers"] = await Mediator.Send(new GetAllTeacherQuery());
            return View(await Mediator.Send(students));
        }
        public async Task<IActionResult> BestTeacherFilter(BestTeacherFilterQuery bestTeacherFilter)
		{
			return View(await Mediator.Send(bestTeacherFilter));
		}
	}
}

SchoolMonitoringSystem.Api/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using SchoolMonitoringSystem.Api.Filters;
using SchoolMonitoringSystem.Application.UseCases;
using X.PagedList;

namespace SchoolMonitoringSystem.Api.Controllers
{
    public class StudentController : ApiBaseController
    {
        [HttpGet]
        public IActionResult CreateStudent()
        {
            return View();
        }
        [HttpPost]
        [ActionModelValidationAttribute]
        public async Task<IActionResult> CreateStudent(CreateStudentCommand studentCommand)
        {
            await Mediator.Send(studentCommand);
			return RedirectToAction(nameof(GetAllStudents));
		}
        [HttpGet]
        public async Task<IActionResult> GetByStudentId(GetStudentQuery studentQuery)
        {
            var subjects = await Mediator.Send(new GetAllSubjectQuery());
            ViewData["subjects"] = subjects;
            return View(await Mediator.Send(studentQuery));
        }
        [HttpGet]
        [LazyCache(2, 5)]
        [EnableRateLimiting("Token")]
        public async ValueTask<IActionResult> GetAllStudents(int page = 1)
        {
            IPagedList<StudentDto> query = (await Mediator
                .Send(new GetAllStudentQuery()))
                .ToPagedList(page, 5);
            return View(query);
        }
        [HttpGet]
        public IActionResult UpdateStudent(StudentDto studentDto)
        {
            return View(studentDto);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateStudent([FromForm] UpdateStudentCommand studentCommand)
        {
            await Mediator.Send(studentCommand);
            return RedirectToAction(nameof(GetAllStudents));
        }
        [HttpPost]
        public async Task<IActionResult> DeleteStudent(DeleteStudentCommand studentCommand)
        {
            var result = await Mediator.Send(studentCommand);
            return RedirectToAction(nameof(GetAllStudents));
        }
    }
}

SchoolMonitoringSystem.Api/Views/Student/CreateStudent.cshtml
@model SchoolMonitoringSystem.Application.UseCases.CreateStudentCommand
<!DOCTYPE html>
<html>
<head>
    <title>Talaba yaratish</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            margin: 0;
            padding: 0;
        }

        .full-page-background {
            background-image: url('/images/340434.jpg');
            background-size: cover;
            background-position: center;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            color: black;
            text-align: center;
            font-size: 1.5rem;
        }

        .align-content-xl-center {
            display: flex;
            flex-wrap: wrap;
            align-content: center;
            justify-content: center;
            height: 100%;
        }

        .display-4 {
            margin-bottom: 1rem;
            font-size: 3rem;
            font-weight: bold;
        }

        .social-links {
            display: flex;
            gap: 1rem;
            margin-top: 1rem;
        }

            .social-links a {
                color: black;
                text-decoration: none;
            }
    </style>
</head>
<body>
    <div class="full-page-background">
        <div class="container">
            <h1>Talaba yaratish</h1>
            <form id="create-form" enctype="multipart/form-data" method="post" action="/student/createstudent">
                <div class="form-group">
                    <label for="FirstName">Ism:</label>
                    <input type="text" class="form-control" id="FirstName" name="FirstName" placeholder="Ismni kiriting" required>
                </div>
                <div class="form-group">
                    <label for="LastName">Familiya:</label>
                    <input type="text" class="form-control" id="LastName" name="LastName" placeholder="Familiyani kiriting" required>
                </div>
                <div class="form-group">
                    <label for="BirthDate">Tug'ilgan sanasi:</label>
                    <input type="date" class="form-control" id="BirthDate" name="BirthDate" placeholder="Tug'ilgan sanani kiriting" required>
                </div>
                <div class="form-group">
                    <label for="Email">Elektron pochta:</label>
                    <input type="email" class="form-control" id="Email" name="Email" placeholder="Elektron pochtani kiriting" required>
                </div>
                <div class="form-group">
                    <label for="PhoneNumber">Telefon raqami:</label>
                    <input type="tel" class="form-control" id="PhoneNumber" name="PhoneNumber" placeholder="Telefon raqamini kiriting" required pattern="^\+998\d{9}$" title="Telefon raqami to'g'ri formatda bo'lishi kerak: +998 va 9 ta raqam">
                    <span class="text-danger" id="phoneNumberError"></span>
                </div>
                <div class="form-group">
                    <label for="StudentRegNumber">Student raqami:</label>
                    <input type="text" class="form-control" id="StudentRegNumber" name="StudentRegNumber" placeholder="Student raqamini kiriting" required>
                </div>
                <div class="form-group">
                    <label asp-for="Img" class="control-label">Rasm</label>
                    <input type="file" asp-for="Img" class="form-control-file" id="Img" required>
                    <span asp-validation-for="Img" class="text-danger" id="imgError"></span>
                </div>
                <div class="d-flex justify-content-between">
                    <a href="/student/getallstudents" class="btn btn-info"><i class="fas fa-arrow-left"></i> Orqaga</a>
                    <button type="submit" class="btn btn-danger" id="createButton">Yaratish</button>
                </div>
            </form>
        </div>
    </div>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        createButton.addEventListener("click", function (event) {
            if (!validateForm()) {
                event.preventDefault();
            }
        });

        function validateForm() {
            var firstName = document.getElementById("FirstName").value;
            var lastName = document.getElementById("LastName").value;
            var birthDate = document.getElementById("BirthDate").value;
            var email = document.getElementById("Email").value;
            var phoneNumber = document.getElementById("PhoneNumber").value;
            var studentRegNumber = document.getElementById("StudentRegNumber").value;
            var imgInput = document.getElementById("Img");
            var file = imgInput.files[0];
            var imgError = document.getElementById("imgError");
            var allowedExtensions = /(\.jpg|\.jpeg)$/i;

            if (!firstName || !lastName || !birthDate || !email || !phoneNumber || !studentRegNumber) {
                alert("Iltimos, barcha maydonlarni to'ldiring!");
                return false;
            }

            if (!file) {
                imgError.textContent = 'Rasm yuklash shart.';
                return false;
            }

            if (!allowedExtensions.exec(file.name)) {
                imgError.textContent = 'Faqat JPG va JPEG formatidagi rasm fayllarini yuklang.';
                return false;
            }

            imgError.textContent = '';
            return true;
        }
    </script>
</body>
</html>

SchoolMonitoringSystem.Api/Views/Student/GetAllStudents.cshtml
@using SchoolMonitoringSystem.Application.Common.Exceptions;
@using SchoolMonitoringSystem.Application.UseCases;
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@model IEnumerable<StudentDto>
<!DOCTYPE html>
<html>
<head>
    <title>Barcha Studentlar</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        /* CSS Stilleri */
        .edit-button {
            float: right;
        }

        .update-form {
            display: none;
            margin-top: 10px;
        }

        .notification {
            margin-top: 10px;
        }

        body {
            margin: 0;
            padding: 0;
        }

        .full-page-background {
            background-image: url('/images/340434.jpg');
            background-size: cover;
            background-position: center;
            height: 100vh;
            padding-top: 50px;
            color: black;
            text-align: center;
            font-size: 1.5rem;
        }

        .align-content-xl-center {
            display: flex;
            flex-wrap: wrap;
            align-content: center;
            justify-content: center;
            height: 100%;
        }

        .display-4 {
            margin-bottom: 1rem;
            font-size: 3rem;
            font-weight: bold;
        }

        .social-links {
            display: flex;
            gap: 1rem;
            margin-top: 1rem;
        }

            .social-links a {
                color: black;
                text-decoration: none;
            }
    </style>
</head>
<body>
    <div class="full-page-background">
    <div class="container">
        @if (TempData["CreateMessage"] != null)
        {
            <div class="notification alert alert-success">
                @TempData["CreateMessage"]
            </div>
        }
        @if (TempData["UpdateMessage"] != null)
        {
            <div class="notification alert alert-info">
                @TempData["UpdateMessage"]
            </div>
        }
        @if (TempData["DeleteMessage"] != null)
        {
            <div class="notification alert alert-danger">
                @TempData["DeleteMessage"]
            </div>
        }

        <div class="d-flex justify-content-between align-items-center">
            <h1>Barcha Studentlar</h1>
            <button id="create-button" class="btn btn-primary" onclick="location.href='/student/createstudent'">+</button>
        </div>

        <div class="input-group mb-3">
            <form action="@Url.Action("SearchStudentFilter", "Filter")" method="get">
            <input type="text" name="SearchPattern" placeholder="Enter search term" />
            <button type="submit">Qidirish</button>
            </form>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>FirstName</th>
                    <th>LastName</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var student in Model)
                {
                    <tr>
                        <td>@student.FirstName</td>
                        <td>@student.LastName</td>
                        <td>
                            <a href ="@Url.Action("GetByStudentId" , student)" class="btn btn-info">Batafsil</a>
                        </td>
                        <td>
                            <a href ="@Url.Action("UpdateStudent" , student)" class="btn btn-outline-primary">Tahrirlash</a>
                        </td>
                        <td>
                            <form method="post" action="/student/deletestudent/@student.Id" class="delete-form">
                                <button type="submit" class="btn btn-danger">O'chirish</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="container fixed-bottom d-flex align-items-center justify-content-center">
            @Html.PagedListPager((IPagedList)Model,page => Url.Action("GetAllStudents", "Student",new{ page= page}),
            new X.PagedList.Web.Common.PagedListRenderOptions
            {
            DisplayItemSliceAndTotal = false,
            ContainerDivClasses = new[] { "navigation" },
            LiElementClasses = new[] { "page-item" },
            PageClasses = new[] { "page-link" },
            })
        </div>
    </div>
    </div>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        const createButton = document.getElementById('create-button');
        const createForm = document.getElementById('create-form');
        const searchButton = document.getElementById('search-button');
        const searchInput = document.getElementById('search-input');

        createButton.addEventListener('click', function () {
            createForm.style.display = 'block';
        });

        searchButton.addEventListener('click', function () {
            const searchTerm = searchInput.value.toLowerCase();
            const tableRows = document.getElementsByTagName('tr');

            for (let i = 0; i < tableRows.length; i++) {
                const row = tableRows[i];
                const firstName = row.getElementsByTagName('td')[0].innerText.toLowerCase();
                const lastName = row.getElementsByTagName('td')[1].innerText.toLowerCase();

                if (firstName.includes(searchTerm) || lastName.includes(searchTerm)) {
                    row.style.display = 'table-row';
                } else {
                    row.style.display = 'none';
                }
            }
        });

        function editStudent(id) {
            const editForm = document.querySelector('.update-form[data-student-id="' + id + '"]');
            const editButton = editForm.querySelector('.edit-button');

            if (editForm.style.display === 'none') {
                editForm.style.display = 'block';
                editButton.innerText = "Bekor qilish";
            } else {
                editForm.style.display = 'none';
                editButton.innerText = "Tahrirlash";
            }
        }

    </script>
</body>
</html>

SchoolMonitoringSystem.Api/Views/Student/GetByStudentId.cshtml
@using SchoolMonitoringSystem.Application.Common.Exceptions;
@using SchoolMonitoringSystem.Application.UseCases
@model GetStudentsWithGrades
@{
    List<SubjectDto> subjects = ViewData["subjects"] as List<SubjectDto>;
}

<!DOCTYPE html>
<html>
<head>
    <title>Talabalar Ro'yxati</title>
      <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 20px;
        }
        
        .details-form {
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            padding: 20px;
            max-width: 500px;
            margin: 0 auto;
        }
        
        h2 {
            font-size: 24px;
            margin-bottom: 20px;
            color: #333;
        }
        
        p {
            margin: 10px 0;
            color: #555;
        }
        
        strong {
            font-weight: bold;
        }

        body {
            margin: 0;
            padding: 0;
        }

        .full-page-background {
            background-image: url('/images/340434.jpg');
            background-size: cover;
            background-position: center;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            color: black;
            text-align: center;
            font-size: 1.5rem;
        }

        .align-content-xl-center {
            display: flex;
            flex-wrap: wrap;
            align-content: center;
            justify-content: center;
            height: 100%;
        }

        .display-4 {
            margin-bottom: 1rem;
            font-size: 3rem;
            font-weight: bold;
        }

        .social-links {
            display: flex;
            gap: 1rem;
            margin-top: 1rem;
        }

            .social-links a {
                color: black;
                text-decoration: none;
            }
    </style>
</head>

<body>    
    <div class="full-page-background">
        <div class="details-form" data-student-id="@Model.Id">
            <h2>Talaba ma'lumotlari</h2>

            <img decoding="async" src="@Url.Content("~/" + @Model.Img)" width="250px" height="250px" />
            <p><strong>Ism:</strong> @Model.FirstName</p>
            <p><strong>Familiya:</strong> @Model.LastName</p>
            <p><strong>Tug'ilgan sanasi:</strong> @Model.BirthDate</p>
            <p><strong>Elektron pochta:</strong> @Model.Email</p>
            <p><strong>Telefon raqami:</strong> @Model.PhoneNumber</p>
            <p><strong>Student raqami:</strong> @Model.StudentRageNumber</p>
            @if (subjects != null && Model.Grades != null && Model.Grades.Any())
            {
                var maxGradeSubject = (from subject in subjects
                                       join grade in Model.Grades on subject.Id equals grade.SubjectId
                                       orderby grade.Ball descending
                                       select subject).FirstOrDefault();
                <p><strong>Eng yuqori ball toʻplagan fan:</strong> @maxGradeSubject.SubjectName</p>
            }
            <div class="d-flex justify-content-between">
                <a href="/student/getallstudents" class="btn btn-info"><i class="fas fa-arrow-left"></i> Orqaga</a>
            </div>
        </div>
    </div>
</body>
</html>

SchoolMonitoringSystem.Api/Views/Student/UpdateStudent.cshtml
@using SchoolMonitoringSystem.Application.UseCases
@model SchoolMonitoringSystem.Application.UseCases.StudentDto


<!DOCTYPE html>
<html>
<head>
    <title>Talabaning ma'lumotlarini tahrirlash</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            padding: 20px;
        }

        .update-form {
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            padding: 20px;
            max-width: 500px;
            margin: 0 auto;
        }

        h2 {
            font-size: 24px;
            margin-bottom: 20px;
            color: #333;
        }

        form {
            display: inline;
            gap: 1px;
        }

        label {
            font-weight: bold;
        }

        input[type="text"],
        input[type="number"],
        input[type="date"] {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        input[type="submit"] {
            background-color: #4caf50;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
        }

            input[type="submit"]:hover {
                background-color: #45a049;
            }

        body {
            margin: 0;
            padding: 0;
        }

        .full-page-background {
            background-image: url('/images/340434.jpg');
            background-size: cover;
            background-position: center;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            color: black;
            text-align: center;
            font-size: 1.5rem;
        }

        .align-content-xl-center {
            display: flex;
            flex-wrap: wrap;
            align-content: center;
            justify-content: center;
            height: 100%;
        }

        .display-4 {
            margin-bottom: 1rem;
            font-size: 3rem;
            font-weight: bold;
        }

        .social-links {
            display: flex;
            gap: 1rem;
            margin-top: 1rem;
        }

            .social-links a {
                color: black;
                text-decoration: none;
            }
    </style>
        <title>Student ma'lumotlarini tahrirlash</title>
    </head>
    <body>
        <div class="full-page-background">
            <div class="update-form">
                <h2>Student ma'lumotlarini tahrirlash</h2>
            <form id="updateForm" enctype="multipart/form-data" action="/student/updatestudent" method="POST">
                <input type="hidden" id="id" name="id" value="@Model.Id">
                    <label for="FirstName">Ism:</label>
                    <input type="text" id="FirstName" name="FirstName" value="@Model.FirstName" required>
                    <label for="LastName">Familiya:</label>
                    <input type="text" id="LastName" name="LastName" value="@Model.LastName" required>
                    <label for="PhoneNumber">Telefon raqami:</label>
                    <input type="tel" id="PhoneNumber" name="PhoneNumber" value="@Model.PhoneNumber" pattern="^\+998\d{9}$" title="Telefon raqami to'g'ri formatda bo'lishi kerak: +998 va 9 ta raqam" required>
                    <span class="text-danger" id="phoneNumberError"></span>
                    <label for="Birthdate">Tug'ilgan sanasi:</label>
                    <input type="date" id="Birthdate" name="Birthdate" value="@Model.BirthDate" required>
                    <label for="Email">Elektron pochta:</label>
                    <input type="email" id="Email" name="Email" value="@Model.Email" required>
                    <label for="StudentRegNumber">Student raqami:</label>
                    <input type="text" id="StudentRegNumber" name="StudentRegNumber" value="@Model.StudentRageNumber" required>
                    <div class="form-group">
                        <label asp-for="Img" class="control-label">Rasm</label>
                        <input type="file" id="Img" name="Img" class="form-control-file" />
                        <span class="text-danger" id="imgError"></span>
                    </div>
                <input type="submit" value="Submit" onclick="return validateForm();">
            </form>
            </div>
        </div>
    <script>
        function validateForm() {
            var firstName = document.getElementById("FirstName").value;
            var lastName = document.getElementById("LastName").value;
            var birthDate = document.getElementById("Birthdate").value;
            var email = document.getElementById("Email").value;
            var phoneNumber = document.getElementById("PhoneNumber").value;
            var studentRegNumber = document.getElementById("StudentRegNumber").value;
            var imgInput = document.getElementById("Img");
            var file = imgInput.files[0];
            var imgError = document.getElementById("imgError");
            var allowedExtensions = /(\.jpg|\.jpeg)$/i;

            if (!firstName || !lastName || !birthDate || !email || !phoneNumber || !studentRegNumber) {
                alert("Iltimos, barcha maydonlarni to'ldiring!");
                return false;
            }

            if (file && !allowedExtensions.exec(file.name)) {
                imgError.textContent = 'Faqat JPG va JPEG formatidagi rasm fayllarini yuklang.';
                return false;
            }

            imgError.textContent = '';
            return true;
        }
    </script>
    </body>
</html>