SchoolMonitoringSystem.Api/Controllers/GradeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.RateLimiting;
using SchoolMonitoringSystem.Api.Filters;
using SchoolMonitoringSystem.Application;
using SchoolMonitoringSystem.Application.UseCases;
using X.PagedList;

namespace SchoolMonitoringSystem.Api.Controllers
{
    public class GradeController : ApiBaseController
    {
        [HttpGet]
        public async Task<IActionResult> CreateGrade()
        {
            var students = await Mediator.Send(new GetAllStudentQuery());
            var subjects = await Mediator.Send(new GetAllSubjectQuery());
            ViewData["subjects"] = subjects;
            ViewData["students"] = students;
            return View();
        }
        [HttpPost]
        [ActionModelValidationAttribute]
        public async Task<IActionResult> CreateGrade(CreateGradeCommand gradeCommand)
        {
            var result = await Mediator.Send(gradeCommand);
            return RedirectToAction(nameof(GetAllGrades));
        }
        [HttpGet]
        [LazyCache(2, 5)]
        [EnableRateLimiting("Token")]
        public async Task<IActionResult> GetAllGrades(int page = 1)
        {
            ViewData["students"] = await Mediator.Send(new GetAllStudentQuery());
            ViewData["subjects"] = await Mediator.Send(new GetAllSubjectQuery());
            IPagedList<GradeDto> query = (await Mediator
                .Send(new GetAllGradeQuery()))
                .ToPagedList(page, 5);
            return View(query);
        }
        [HttpGet]
        public IActionResult UpdateGrade(GradeDto gradeDto)
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> UpdateGrade([FromForm] UpdateGradeCommand gradeCommand)
        {
            var result = await Mediator.Send(gradeCommand);
            return RedirectToAction(nameof(GetAllGrades));
        }
        [HttpPost]
        public async Task<IActionResult> DeleteGrade(DeleteGradeCommand gradeCommand)
        {
            var result = await Mediator.Send(gradeCommand);
            return RedirectToAction(nameof(GetAllGrades));
        }
    }
}

SchoolMonitoringSystem.Api/Views/Grade/CreateGrade.cshtml
@using SchoolMonitoringSystem.Application.UseCases
@model GradeDto
@{
    var students = ViewData["students"] as List<StudentDto>;
    var subjects = ViewData["subjects"] as List<SubjectDto>;
}
<!DOCTYPE html>
<html>
<head>
    <title>Yaratish</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        /* CSS Stilleri */
        .form-container {
            max-width: 500px;
            margin: 0 auto;
            margin-top: 50px;
        }

        .notification {
            margin-top: 10px;
        }

        body {
            margin: 0;
            padding: 0;
        }

        .full-page-background {
            background-image: url('/images/340434.jpg');
            background-size: cover;
            background-position: center;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            color: black;
            text-align: center;
            font-size: 1.5rem;
        }

        .align-content-xl-center {
            display: flex;
            flex-wrap: wrap;
            align-content: center;
            justify-content: center;
            height: 100%;
        }

        .display-4 {
            margin-bottom: 1rem;
            font-size: 3rem;
            font-weight: bold;
        }

        .social-links {
            display: flex;
            gap: 1rem;
            margin-top: 1rem;
        }

            .social-links a {
                color: black;
                text-decoration: none;
            }
    </style>
</head>
<body>
    <div class="full-page-background">
    <div class="container">
        <div class="form-container">
            <h2>Yaratish</h2>
            <form action="/grade/creategrade" method="POST">
                @if (TempData["ErrorMessage"] != null)
                {
                    <div class="notification alert alert-danger">
                        @TempData["ErrorMessage"]
                    </div>
                }
                <div>
                     <select class="form-control" id="StudentId" name="StudentId" required>
                         <option value="">Studentni tanlang</option>
                         @foreach (var student in students)
                         {
                             <option value="@student.Id">@student.FirstName  @student.LastName</option>
                         }
                     </select>
                </div>
                <div>
                     <select class="form-control" id="SubjectId" name="SubjectId" required>
                         <option value="">Fanni tanlang</option>
                         @foreach (var subject in subjects)
                         {
                             <option value="@subject.Id">@subject.SubjectName</option>
                         }
                     </select>
                </div>
                <div class="form-group">
                    <label for="Ball">Ball:</label>
                    <input type="number" id="Ball" name="Ball" class="form-control" required>
                </div>
                <div class="d-flex justify-content-between">
                <a href="/grade/getallgrades" class="btn btn-info"><i class="fas fa-arrow-left"></i> Orqaga</a>
                <button type="submit" class="btn btn-danger">Yaratish</button>
            </div>
            </form>
        </div>
    </div>
    </div>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

SchoolMonitoringSystem.Api/Views/Grade/GetAllGrades.cshtml
@using SchoolMonitoringSystem.Application.UseCases
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@model IEnumerable<GradeDto>
@{
    var students = ViewData["students"] as List<StudentDto>;
    var subjects = ViewData["subjects"] as List<SubjectDto>;
}

<!DOCTYPE html>
<html>
<head>
    <title>Barcha Natijalar</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        /* CSS Stilleri */
        .edit-button {
            float: right;
        }

        .update-form {
            display: none;
            margin-top: 10px;
        }

        .notification {
            margin-top: 10px;
        }

        body {
            margin: 0;
            padding: 0;
        }

        .full-page-background {
            background-image: url('/images/340434.jpg');
            background-size: cover;
            background-position: center;
            height: 100vh;
            padding-top: 50px;
            align-items: center;
            color: black;
            text-align: center;
            font-size: 1.5rem;
        }

        .align-content-xl-center {
            display: flex;
            flex-wrap: wrap;
            align-content: center;
            justify-content: center;
            height: 100%;
        }

        .display-4 {
            margin-bottom: 1rem;
            font-size: 3rem;
            font-weight: bold;
        }

        .social-links {
            display: flex;
            gap: 1rem;
            margin-top: 1rem;
        }

            .social-links a {
                color: black;
                text-decoration: none;
            }
    </style>
</head>
<body>
    <div class="full-page-background">
    <div class="container">
        @if (TempData["CreateMessage"] != null)
        {
            <div class="notification alert alert-success">
                @TempData["CreateMessage"]
            </div>
        }
        @if (TempData["UpdateMessage"] != null)
        {
            <div class="notification alert alert-info">
                @TempData["UpdateMessage"]
            </div>
        }
        @if (TempData["DeleteMessage"] != null)
        {
            <div class="notification alert alert-danger">
                @TempData["DeleteMessage"]
            </div>
        }
        <div class="d-flex justify-content-between align-items-center">
            <h1>Barcha Natijalar</h1>
            <button id="create-button" class="btn btn-primary" onclick="location.href='/grade/creategrade'">+</button>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>FirstName</th>
                    <th>LastName</th>
                    <th>Subject</th>
                    <th>Ball</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var grade in Model)
                {
                    StudentDto? student = students.FirstOrDefault(s => s.Id == grade.StudentId);
                    SubjectDto? subjectDto = subjects.FirstOrDefault(s => s.Id == grade.SubjectId);
                    <tr>
                        <td>@student.FirstName</td>
                        <td>@student.LastName</td>
                        <td>@subjectDto.SubjectName</td>
                        <td>@grade.Ball</td>
                        <td>
                            <button onclick="editGrade('@grade.Id')" class="btn btn-outline-primary edit-button">Tahrirlash</button>
                        </td>
                        <td>
                            <form method="post" action="/grade/deletegrade/@grade.Id" class="delete-form">
                                <button type="submit" class="btn btn-danger">O'chirish</button>
                            </form>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <div class="update-form" data-grade-id="@grade.Id" style="display: none;">
                                <h2>Dereceni tahrirlash</h2>
                                <form action="/grade/updategrade" method="POST">
                                    <input type="hidden" id="id" name="id" value="@grade.Id">
                                    
                                    <label for="Ball">Ball:</label>
                                    <input type="number" id="Ball" name="Ball" value="@grade.Ball" required>
                                    <input type="submit" value="Submit">
                                </form>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="container fixed-bottom d-flex align-items-center justify-content-center">
            @Html.PagedListPager((IPagedList)Model,page => Url.Action("GetAllGrades", "Grade",new{ page= page}),
            new X.PagedList.Web.Common.PagedListRenderOptions
            {
            DisplayItemSliceAndTotal = false,
            ContainerDivClasses = new[] { "navigation" },
            LiElementClasses = new[] { "page-item" },
            PageClasses = new[] { "page-link" },
            })
        </div>
    </div>
    </div>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        const createButton = document.getElementById('create-button');
        const createForm = document.getElementById('create-form');

        createButton.addEventListener('click', function () {
            createForm.style.display = 'block';
        });

        function editGrade(id) {
            const editForm = document.querySelector('.update-form[data-grade-id="' + id + '"]');
            const editButton = editForm.querySelector('.edit-button');

            if (editForm.style.display === 'none') {
                editForm.style.display = 'block';
                editButton.innerText = "Bekor qilish";
            } else {
                editForm.style.display = 'none';
                editButton.innerText = "Tahrirlash";
            }
        }
    </script>
</body>
</html>