SchoolMonitoringSystem.Api/Controllers/FilterController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolMonitoringSystem.Application.Common;
using SchoolMonitoringSystem.Application.UseCases;
using SchoolMonitoringSystem.Application.UseCases.Filters;

namespace SchoolMonitoringSystem.Api.Controllers
{
    public class FilterController : ApiBaseController
    {
        private readonly IApplicationDbContext dbContext;

        public FilterController(IApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public async Task<IActionResult> AgeStudentFilter(AgeStudentFilterQuery ageFilterQuery)
        {
            return View(await Mediator.Send(ageFilterQuery));
        }
        public async Task<IActionResult> DayMonthFilter(DayMonthFilterQuery dayMonthFilter)
        {
            return View(await Mediator.Send(dayMonthFilter));
        }
		public async Task<IActionResult> AgeTeacherFilter(AgeTeacherFilterQuery ageTeacherFilterQuery)
		{
			return View(await Mediator.Send(ageTeacherFilterQuery));
		}
        public async Task<IActionResult> IsBeelineStudentFilter(IsBeelineStudentFilterQuery isBeelineStudentFilter)
		{
			return View(await Mediator.Send(isBeelineStudentFilter));
		}
        public async Task<IActionResult> IsBeelineTeacherFilter(IsBeelineTeacherFilterQuery isBeelineTeacherFilter)
		{
			return View(await Mediator.Send(isBeelineTeacherFilter));
		}
        public async Task<IActionResult> SearchStudentFilter(SearchStudentFilterQuery searchStudentFilter)
		{
			return View(await Mediator.Send(searchStudentFilter));
		}
        public async Task<IActionResult> SearchSubjectFilter(SearchSubjectFilterQuery searchSubjectFilter)
		{
            ViewData["teachers"] = await Mediator.Send(new GetAllTeacherQuery());
            return View(await Mediator.Send(searchSubjectFilter));
		}
        public async Task<IActionResult> SearchTeacherFilter(SearchTeacherFilterQuery searchTeacherFilter)
		{
			return View(await Mediator.Send(searchTeacherFilter));
		}
        [HttpGet]
        public async Task<IActionResult> BestSubjectFilter()
        {
            ViewData["teachers"] = await Mediator.Send(new GetAllTeacherQuery());
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> BestSubjectsFilter(BestSubjectFilterQuery students)
        {
            ViewData["teachers"] = await Mediator.Send(new GetAllTeacherQuery());
            return View(await Mediator.Send(students));
        }
        public async Task<IActionResult> BestTeacherFilter(BestTeacherFilterQuery bestTeacherFilter)
		{
			return View(await Mediator.Send(bestTeacherFilter));
		}
	}
}

SchoolMonitoringSystem.Api/Controllers/SubjectController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using SchoolMonitoringSystem.Api.Filters;
using SchoolMonitoringSystem.Application.UseCases;
using X.PagedList;

namespace SchoolMonitoringSystem.Api.Controllers
{
    public class SubjectController : ApiBaseController
    {
        [HttpGet]
        public async Task<IActionResult> CreateSubject()
        {
            var teachers = await Mediator.Send(new GetAllTeacherQuery());
            ViewData["teachers"] = teachers;
            return View();
        }
        [HttpPost]
        [ActionModelValidationAttribute]
        public async Task<IActionResult> CreateSubject(CreateSubjectCommand subjectCommand)
        {
            var result = await Mediator.Send(subjectCommand);
            return RedirectToAction(nameof(GetAllSubjects));
        }
        [HttpGet]
        [LazyCache(2, 5)]
        [EnableRateLimiting("Token")]
        public async ValueTask<IActionResult> GetAllSubjects(int page = 1)
        {
            ViewData["teachers"] = await Mediator.Send(new GetAllTeacherQuery());
            IPagedList<SubjectDto> query = (await Mediator
                .Send(new GetAllSubjectQuery()))
                .ToPagedList(page, 5);
            return View(query);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateSubject([FromForm] UpdateSubjectCommand subjectCommand)
        {
            var result = await Mediator.Send(subjectCommand);
            return RedirectToAction(nameof(GetAllSubjects));
        }
        [HttpPost]
        public async Task<IActionResult> DeleteSubject(DeleteSubjectCommand subjectCommand)
        {
            var result = await Mediator.Send(subjectCommand);
            return RedirectToAction(nameof(GetAllSubjects));
        }
    }
}

SchoolMonitoringSystem.Api/Views/Subject/CreateSubject.cshtml
@using SchoolMonitoringSystem.Application.UseCases
@model SubjectDto
@{
    var teachers = ViewData["teachers"] as List<TeacherDto>;
}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Create Subject - School Monitoring System</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            margin: 0;
            padding: 0;
        }

        .full-page-background {
            background-image: url('/images/340434.jpg');
            background-size: cover;
            background-position: center;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            color: black;
            text-align: center;
            font-size: 1.5rem;
        }

        .align-content-xl-center {
            display: flex;
            flex-wrap: wrap;
            align-content: center;
            justify-content: center;
            height: 100%;
        }

        .display-4 {
            margin-bottom: 1rem;
            font-size: 3rem;
            font-weight: bold;
        }

        .social-links {
            display: flex;
            gap: 1rem;
            margin-top: 1rem;
        }

            .social-links a {
                color: black;
                text-decoration: none;
            }
    </style>
</head>
<body>
    <div class="full-page-background">
  <div class="container">
    <form id="create-form" method="post" action="/subject/createsubject">
      <h1>Fan yaratish</h1>
      <div class="row justify-content-between">
        <div class="col-md-4">
          <div class="form-group">
            <label for="SubjectName">Fan nomi:</label>
            <input type="text" class="form-control" id="SubjectName" name="SubjectName" placeholder="Fan nomini kiriting" required>
          </div>
          <div class="mt-3">
            <input type="submit" value="Yaratish" class="btn btn-primary">
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <label for="TeacherId">O'qituvchi:</label>
            <select class="form-control" id="TeacherId" name="TeacherId" required>
              <option value="">O'qituvchini tanlang</option>
              @foreach (var teacher in teachers)
              {
                  <option value="@teacher.Id">@teacher.FirstName @teacher.LastName</option>
              }
            </select>
          </div>
        </div>
      </div>
    </form>
  </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

SchoolMonitoringSystem.Api/Views/Subject/GetAllSubjects.cshtml
@using SchoolMonitoringSystem.Application.Common.Exceptions;
@using SchoolMonitoringSystem.Application.UseCases
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@model IEnumerable<SubjectDto>
@{
    List<TeacherDto> teacherDtos = ViewData["teachers"] as List<TeacherDto>;
}
<!DOCTYPE html>
<html>
<head>
    <title>Barcha Fanlar</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        /* CSS Stilleri */
        .edit-button {
            float: right;
        }

        .update-form {
            display: none;
            margin-top: 10px;
        }

        body {
            margin: 0;
            padding: 0;
        }

        .full-page-background {
            background-image: url('/images/340434.jpg');
            background-size: cover;
            background-position: center;
            height: 100vh;
            padding-top: 50px;
            align-items: center;
            color: black;
            text-align: center;
            font-size: 1.5rem;
        }

        .align-content-xl-center {
            display: flex;
            flex-wrap: wrap;
            align-content: center;
            justify-content: center;
            height: 100%;
        }

        .display-4 {
            margin-bottom: 1rem;
            font-size: 3rem;
            font-weight: bold;
        }

        .social-links {
            display: flex;
            gap: 1rem;
            margin-top: 1rem;
        }

            .social-links a {
                color: black;
                text-decoration: none;
            }
    </style>
</head>
<body>
    <div class="full-page-background">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <h1>Barcha Fanlar</h1>
            <button id="create-button" class="btn btn-primary">+</button>
        </div>
            <div class="input-group mb-3">
                <form action="@Url.Action("SearchSubjectFilter", "Filter")" method="get">
                    <input type="text" name="SearchPattern" placeholder="Enter search term" />
                    <button type="submit">Qidirish</button>
                </form>
            </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Teacher First Name</th>
                    <th>Teacher Last Name</th>
                    <th>Subject Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var subject in Model)
                {
                    TeacherDto teacherDto = teacherDtos.FirstOrDefault(t => t.Id == subject.TeacherId);
                    <tr>
                        <td>@teacherDto.FirstName</td>
                        <td>@teacherDto.LastName</td>
                        <td>@subject.SubjectName</td>
                        <td>
                            <button onclick="editSubject('@subject.Id')" class="btn btn-outline-primary">Tahrirlash</button>
                        </td>
                        <td>
                            <form method="post" action="/subject/deletesubject/@subject.Id" class="delete-form">
                                <button type="submit" class="btn btn-danger">O'chirish</button>
                            </form>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="4">
                            <div class="update-form" data-subject-id="@subject.Id" style="display: none;">
                                <h2>Fanni tahrirlash</h2>
                                <form class="d-flex align-items-center justify-content-between" action="/subject/updatesubject" method="POST">
                                    <div>
                                        <input type="hidden" id="id" name="id" value="@subject.Id">
                                        <label for="SubjectName">Fan nomi:</label><br>
                                        <input class="my-2 rounded-3 p-1" type="text" id="SubjectName" name="SubjectName" value="@subject.SubjectName" required><br>
                                        <input class="btn btn-primary border-0" type="submit" value="Submit">
                                    </div>
                                    <div class="col-md-4">
                                        <label for="TeacherId">O'qituvchi:</label>
                                        <select class="form-control" id="TeacherId" name="TeacherId" required>
                                            <option value="">O'qituvchini tanlang</option>
                                            @foreach (var teacher in teacherDtos)
                                            {
                                                <option value="@teacher.Id">@teacher.FirstName @teacher.LastName</option>
                                            }
                                        </select>
                                    </div>
                                </form>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="container fixed-bottom d-flex align-items-center justify-content-center">
            @Html.PagedListPager((IPagedList)Model,page => Url.Action("GetAllSubjects", "Subject",new{ page= page}),
            new X.PagedList.Web.Common.PagedListRenderOptions
            {
            DisplayItemSliceAndTotal = false,
            ContainerDivClasses = new[] { "navigation" },
            LiElementClasses = new[] { "page-item" },
            PageClasses = new[] { "page-link" },
            })
        </div>
    </div>
    </div>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        const createButton = document.getElementById('create-button');
        const createForm = document.getElementById('create-form');

        document.getElementById("create-button").addEventListener("click", function() {
        window.location.href = "/subject/createsubject"; });

        function editSubject(id) {
            const editForm = document.querySelector('.update-form[data-subject-id="' + id + '"]');
            const editButton = editForm.querySelector('.edit-button');

            if (editForm.style.display === 'none') {
                editForm.style.display = 'block';
                editButton.innerText = "Bekor qilish";
            } else {
                editForm.style.display = 'none';
                editButton.innerText = "Tahrirlash";
            }
        }
    </script>
</body>
</html>