SchoolMonitoringSystem.Api/Controllers/FilterController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolMonitoringSystem.Application.Common;
using SchoolMonitoringSystem.Application.UseCases;
using SchoolMonitoringSystem.Application.UseCases.Filters;

namespace SchoolMonitoringSystem.Api.Controllers
{
    public class FilterController : ApiBaseController
    {
        private readonly IApplicationDbContext dbContext;

        public FilterController(IApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public async Task<IActionResult> AgeStudentFilter(AgeStudentFilterQuery ageFilterQuery)
        {
            return View(await Mediator.Send(ageFilterQuery));
        }
        public async Task<IActionResult> DayMonthFilter(DayMonthFilterQuery dayMonthFilter)
        {
            return View(await Mediator.Send(dayMonthFilter));
        }
		public async Task<IActionResult> AgeTeacherFilter(AgeTeacherFilterQuery ageTeacherFilterQuery)
		{
			return View(await Mediator.Send(ageTeacherFilterQuery));
		}
        public async Task<IActionResult> IsBeelineStudentFilter(IsBeelineStudentFilterQuery isBeelineStudentFilter)
		{
			return View(await Mediator.Send(isBeelineStudentFilter));
		}
        public async Task<IActionResult> IsBeelineTeacherFilter(IsBeelineTeacherFilterQuery isBeelineTeacherFilter)
		{
			return View(await Mediator.Send(isBeelineTeacherFilter));
		}
        public async Task<IActionResult> SearchStudentFilter(SearchStudentFilterQuery searchStudentFilter)
		{
			return View(await Mediator.Send(searchStudentFilter));
		}
        public async Task<IActionResult> SearchSubjectFilter(SearchSubjectFilterQuery searchSubjectFilter)
		{
            ViewData["teachers"] = await Mediator.Send(new GetAllTeacherQuery());
            return View(await Mediator.Send(searchSubjectFilter));
		}
        public async Task<IActionResult> SearchTeacherFilter(SearchTeacherFilterQuery searchTeacherFilter)
		{
			return View(await Mediator.Send(searchTeacherFilter));
		}
        [HttpGet]
        public async Task<IActionResult> BestSubjectFilter()
        {
            ViewData["teachers"] = await Mediator.Send(new GetAllTeacherQuery());
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> BestSubjectsFilter(BestSubjectFilterQuery students)
        {
            ViewData["teachers"] = await Mediator.Send(new GetAllTeacherQuery());
            return View(await Mediator.Send(students));
        }
        public async Task<IActionResult> BestTeacherFilter(BestTeacherFilterQuery bestTeacherFilter)
		{
			return View(await Mediator.Send(bestTeacherFilter));
		}
	}
}

SchoolMonitoringSystem.Api/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using SchoolMonitoringSystem.Api.Filters;
using SchoolMonitoringSystem.Application.UseCases;
using X.PagedList;

namespace SchoolMonitoringSystem.Api.Controllers
{
    public class TeacherController : ApiBaseController
    {
        [HttpGet]
        public IActionResult CreateTeacher()
        {
            return View();
        }

        [HttpPost]
        [ActionModelValidationAttribute]
        public async Task<IActionResult> CreateTeacher(CreateTeacherCommand teacherCommand)
        {
            await Mediator.Send(teacherCommand);
            return RedirectToAction(nameof(GetAllTeachers));
        }
        [HttpGet]
        public async Task<IActionResult> GetByTeacherId(GetTeacherQuery teacherQuery)
        {
            return View(await Mediator.Send(teacherQuery));
        }

        [HttpGet]
        [LazyCache(2, 5)]
        [EnableRateLimiting("Token")]
        public async Task<IActionResult> GetAllTeachers(int page = 1)
        {
            ViewData["teachers"] = await Mediator.Send(new GetAllTeacherQuery());
            IPagedList<TeacherDto> query = (await Mediator
                .Send(new GetAllTeacherQuery()))
                .ToPagedList(page, 5);
            return View(query);
        }

        [HttpGet]
        public IActionResult UpdateTeacher(TeacherDto teacherDto)
        {
            return View(teacherDto);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateTeacher([FromForm] UpdateTeacherCommand teacherCommand)
        {
            var result = await Mediator.Send(teacherCommand);
            return RedirectToAction(nameof(GetAllTeachers));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteTeacher(DeleteTeacherCommand teacherCommand)
        {
            var result = await Mediator.Send(teacherCommand);
            return RedirectToAction(nameof(GetAllTeachers));
        }
    }
}

SchoolMonitoringSystem.Api/Views/Teacher/CreateTeacher.cshtml
@model SchoolMonitoringSystem.Application.UseCases.CreateTeacherCommand
<!DOCTYPE html>
<html>
<head>
    <title>O'qituvchi yaratish</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            margin: 0;
            padding: 0;
        }

        .full-page-background {
            background-image: url('/images/340434.jpg');
            background-size: cover;
            background-position: center;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            color: black;
            text-align: center;
            font-size: 1.5rem;
        }

        .align-content-xl-center {
            display: flex;
            flex-wrap: wrap;
            align-content: center;
            justify-content: center;
            height: 100%;
        }

        .display-4 {
            margin-bottom: 1rem;
            font-size: 3rem;
            font-weight: bold;
        }

        .social-links {
            display: flex;
            gap: 1rem;
            margin-top: 1rem;
        }

            .social-links a {
                color: black;
                text-decoration: none;
            }
    </style>
</head>
<body>
    <div class="full-page-background">
    <div class="container">
        <h1>O'qituvchi yaratish</h1>
            <form id="create-form" enctype="multipart/form-data" method="post" action="/teacher/createteacher">
                <div class="form-group">
                    <label for="FirstName">Ism:</label>
                    <input type="text" class="form-control" id="FirstName" name="FirstName" placeholder="Ismni kiriting" required>
                </div>
                <div class="form-group">
                    <label for="LastName">Familiya:</label>
                    <input type="text" class="form-control" id="LastName" name="LastName" placeholder="Familiyani kiriting" required>
                </div>
                <div class="form-group">
                    <label for="BirthDate">Tug'ilgan sanasi:</label>
                    <input type="date" class="form-control" id="BirthDate" name="BirthDate" placeholder="Tug'ilgan sanani kiriting" required>
                </div>
                <div class="form-group">
                    <label for="Email">Elektron pochta:</label>
                    <input type="email" class="form-control" id="Email" name="Email" placeholder="Elektron pochtani kiriting" required>
                </div>
                <div class="form-group">
                    <label for="PhoneNumber">Telefon raqami:</label>
                    <input type="tel" class="form-control" id="PhoneNumber" name="PhoneNumber" placeholder="Telefon raqamini kiriting" required pattern="^\+998\d{9}$" title="Telefon raqami to'g'ri formatda bo'lishi kerak: +998 va 9 ta raqam">
                    <span class="text-danger" id="phoneNumberError"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Img" class="control-label">Rasm</label>
                    <input type="file" asp-for="Img" class="form-control-file" id="Img" required>
                    <span asp-validation-for="Img" class="text-danger" id="imgError"></span>
                </div>
                <div class="d-flex justify-content-between">
                    <a href="/teacher/getallteachers" class="btn btn-info"><i class="fas fa-arrow-left"></i> Orqaga</a>
                    <button type="submit" class="btn btn-danger" id="createButton">Yaratish</button>
                </div>
            </form>
    </div>
    </div>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        createButton.addEventListener("click", function (event) {
            if (!validateForm()) {
                event.preventDefault();
            }
        });

        function validateForm() {
            var firstName = document.getElementById("FirstName").value;
            var lastName = document.getElementById("LastName").value;
            var birthDate = document.getElementById("BirthDate").value;
            var email = document.getElementById("Email").value;
            var phoneNumber = document.getElementById("PhoneNumber").value;
            var imgInput = document.getElementById("Img");
            var file = imgInput.files[0];
            var imgError = document.getElementById("imgError");
            var allowedExtensions = /(\.jpg|\.jpeg)$/i;

            if (!firstName || !lastName || !birthDate || !email || !phoneNumber) {
                alert("Iltimos, barcha maydonlarni to'ldiring!");
                return false;
            }

            if (!file) {
                imgError.textContent = 'Rasm yuklash shart.';
                return false;
            }

            if (!allowedExtensions.exec(file.name)) {
                imgError.textContent = 'Faqat JPG va JPEG formatidagi rasm fayllarini yuklang.';
                return false;
            }

            imgError.textContent = '';
            return true;
        }
    </script>
</body>
</html>

SchoolMonitoringSystem.Api/Views/Teacher/GetAllTeachers.cshtml
@using SchoolMonitoringSystem.Application.UseCases;
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@model IEnumerable<TeacherDto>

<!DOCTYPE html>
<html>
<head>
    <title>Barcha O'qituvchilar</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        /* CSS Stilleri */
        .edit-button {
            float: right;
        }

        .delete-button {
            margin-left: 5px;
        }

        .details-button {
            margin-left: 5px;
        }

        .details-table {
            margin-top: 10px;
        }

        body {
            margin: 0;
            padding: 0;
        }

        .full-page-background {
            background-image: url('/images/340434.jpg');
            background-size: cover;
            background-position: center;
            height: 100vh;
            padding-top: 50px;
            align-items: center;
            color: black;
            text-align: center;
            font-size: 1.5rem;
        }

        .align-content-xl-center {
            display: flex;
            flex-wrap: wrap;
            align-content: center;
            justify-content: center;
            height: 100%;
        }

        .display-4 {
            margin-bottom: 1rem;
            font-size: 3rem;
            font-weight: bold;
        }

        .social-links {
            display: flex;
            gap: 1rem;
            margin-top: 1rem;
        }

            .social-links a {
                color: black;
                text-decoration: none;
            }
    </style>
</head>
<body>
    <div class="full-page-background">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <h1>Barcha O'qituvchilar</h1>
            <button id="create-button" class="btn btn-primary" onclick="location.href='/teacher/createteacher'">+</button>
        </div>
         <div class="input-group mb-3">
            <form action="@Url.Action("SearchTeacherFilter", "Filter")" method="get">
            <input type="text" name="SearchPattern" placeholder="Enter search term" />
            <button type="submit">Qidirish</button>
            </form>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>FirstName</th>
                    <th>LastName</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var teacher in Model)
                {
                    <tr>
                        <td>@teacher.FirstName</td>
                        <td>@teacher.LastName</td>
                        <td>
                            <a href ="@Url.Action("GetByTeacherId" , teacher)" class="btn btn-info">Batafsil</a>
                        </td>
                        <td>
                            <a href ="@Url.Action("UpdateTeacher" , teacher)" class="btn btn-outline-primary">Tahrirlash</a>
                        </td>
                        <td>
                            <form method="post" action="/teacher/deleteteacher/@teacher.Id" class="delete-form">
                                <button type="submit" class="btn btn-danger">O'chirish</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="container fixed-bottom d-flex align-items-center justify-content-center">
            @Html.PagedListPager((IPagedList)Model,page => Url.Action("GetAllTeachers", "Teacher",new{ page= page}),
            new X.PagedList.Web.Common.PagedListRenderOptions
            {
            DisplayItemSliceAndTotal = false,
            ContainerDivClasses = new[] { "navigation" },
            LiElementClasses = new[] { "page-item" },
            PageClasses = new[] { "page-link" },
            })
        </div>
    </div>
    </div>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

SchoolMonitoringSystem.Api/Views/Teacher/GetByTeacherId.cshtml
@using SchoolMonitoringSystem.Application.UseCases
@model GetTeacherWithSubjectsDto

<!DOCTYPE html>
<html>
<head>
    <title>O'qituvchilar Ro'yxati</title>
      <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 20px;
        }
        
        .details-form {
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            padding: 20px;
            max-width: 500px;
            margin: 0 auto;
        }
        
        h2 {
            font-size: 24px;
            margin-bottom: 20px;
            color: #333;
        }
        
        p {
            margin: 10px 0;
            color: #555;
        }
        
        strong {
            font-weight: bold;
        }

        body {
            margin: 0;
            padding: 0;
        }

        .full-page-background {
            background-image: url('/images/340434.jpg');
            background-size: cover;
            background-position: center;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            color: black;
            text-align: center;
            font-size: 1.5rem;
        }

        .align-content-xl-center {
            display: flex;
            flex-wrap: wrap;
            align-content: center;
            justify-content: center;
            height: 100%;
        }

        .display-4 {
            margin-bottom: 1rem;
            font-size: 3rem;
            font-weight: bold;
        }

        .social-links {
            display: flex;
            gap: 1rem;
            margin-top: 1rem;
        }

            .social-links a {
                color: black;
                text-decoration: none;
            }
    </style>
</head>

<body> 
    <div class="full-page-background">
        <div class="details-form" data-student-id="@Model.Id">
            <h2>Talaba ma'lumotlari</h2>

            <img decoding="async" src="@Url.Content("~/" + @Model.Img)" width="250px" height="250px" />
            <p><strong>Ism:</strong> @Model.FirstName</p>
            <p><strong>Familiya:</strong> @Model.LastName</p>
            <p><strong>Tug'ilgan sanasi:</strong> @Model.BirthDate</p>
            <p><strong>Elektron pochta:</strong> @Model.Email</p>
            <p><strong>Telefon raqami:</strong> @Model.PhoneNumber</p>
            <strong>Darslar:</strong>
            <ul>
                @foreach (var subject in Model.Subjects.Where(s => s.TeacherId == Model.Id))
                {
                    @subject.SubjectName
                }           
            </ul>
        </div>

        <div class="d-flex justify-content-between">
            <a href="/teacher/getallteachers" class="btn btn-info"><i class="fas fa-arrow-left"></i> Orqaga</a>
        </div>
    </div>


</body>
</html>

SchoolMonitoringSystem.Api/Views/Teacher/UpdateTeacher.cshtml
@using SchoolMonitoringSystem.Application.UseCases;
@model TeacherDto;

<!DOCTYPE html>
<html>
<head>
    <title>O'qituvchi ma'lumotlarini tahrirlash</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            padding: 20px;
        }

        .update-form {
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            padding: 20px;
            max-width: 500px;
            margin: 0 auto;
        }

        h2 {
            font-size: 24px;
            margin-bottom: 20px;
            color: #333;
        }

        form {
            display: grid;
            gap: 10px;
        }

        label {
            font-weight: bold;
        }

        input[type="text"],
        input[type="number"],
        input[type="date"] {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        input[type="submit"] {
            background-color: #4caf50;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
        }

            input[type="submit"]:hover {
                background-color: #45a049;
            }

        body {
            margin: 0;
            padding: 0;
        }

        .full-page-background {
            background-image: url('/images/340434.jpg');
            background-size: cover;
            background-position: center;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            color: black;
            text-align: center;
            font-size: 1.5rem;
        }

        .align-content-xl-center {
            display: flex;
            flex-wrap: wrap;
            align-content: center;
            justify-content: center;
            height: 100%;
        }

        .display-4 {
            margin-bottom: 1rem;
            font-size: 3rem;
            font-weight: bold;
        }

        .social-links {
            display: flex;
            gap: 1rem;
            margin-top: 1rem;
        }

            .social-links a {
                color: black;
                text-decoration: none;
            }
    </style>
</head>
<body>
    <div class="full-page-background">
        <div class="updatee-form">
            <h2>O'qituvchi ma'lumotlarini tahrirlash</h2>
            <form id="updateForm" enctype="multipart/form-data" action="/teacher/updateteacher" method="POST" onsubmit="return validateForm()">
                <input type="hidden" id="id" name="id" value="@Model.Id">
                <label for="FirstName">Ism:</label>
                <input type="text" id="FirstName" name="FirstName" value="@Model.FirstName" required>
                <label for="LastName">Familiya:</label>
                <input type="text" id="LastName" name="LastName" value="@Model.LastName" required>
                <label for="PhoneNumber">Telefon raqami:</label>
                <input type="text" id="PhoneNumber" name="PhoneNumber" value="@Model.PhoneNumber" required>
                <label for="Birthdate">Tug'ilgan sanasi:</label>
                <input type="date" id="Birthdate" name="Birthdate" value="@Model.BirthDate" required>
                <label for="Email">Elektron pochta:</label>
                <input type="text" id="Email" name="Email" value="@Model.Email" required>
                <div class="form-group">
                    <label asp-for="Img" class="control-label">Rasm</label>
                    <input type="file" asp-for="Img" class="form-control-file" />
                    <span asp-validation-for="Img" id="imgError" class="text-danger"></span>
                </div>
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>
    <script>
        function validateForm() {
            var firstName = document.getElementById("FirstName").value;
            var lastName = document.getElementById("LastName").value;
            var birthDate = document.getElementById("Birthdate").value;
            var email = document.getElementById("Email").value;
            var phoneNumber = document.getElementById("PhoneNumber").value;
            var imgInput = document.getElementById("Img");
            var file = imgInput.files[0];
            var imgError = document.getElementById("imgError");
            var allowedExtensions = /(\.jpg|\.jpeg)$/i;

            if (!firstName || !lastName || !birthDate || !email || !phoneNumber) {
                alert("Iltimos, barcha maydonlarni to'ldiring!");
                return false;
            }

            if (file) {
                if (!allowedExtensions.exec(file.name)) {
                    imgError.textContent = 'Faqat JPG va JPEG formatidagi rasm fayllarini yuklang.';
                    return false;
                }
            } else {
                imgError.textContent = 'Iltimos, bir rasm yuklang.';
                return false;
            }

            imgError.textContent = '';
            return true;
        }
    </script>


</body>
</html>